export default {
    Email: "Email",
    Password: "Password",
    Login: "Login",
    Register: "Register",
    ForgotPassword: "Forgot Password",
    ResetPassword: "Reset Password",
    ForgotPasswordLink: "Forgot your password?",
    AlreadyHaveAnAccount: "Already have an account?",
    DontHaveAnAccount: "Don't have an account?",
    RememberMe: "Remember me",
    AlreadyHaveToken: "Already have the code?",
    BackToLogin: "Back to login",
    Send: "Send",
    ForgotPasswordHelper: "Enter your email and we will send you a code to reset your password",
    ResetPasswordHelper1: "Enter the code and your new password",
    ResetPasswordHelper2: "Enter your email, the code and your new password",
    RepeatPassword: "Repeat password",
    Code: "Code",
    PasswordsDontMatch: "Passwords don't match",
    Name: "Name",
};
