export default {
    InvalidEmail: "Invalid email",
    EmailRequired: "The email is required",
    InvalidPassword:
        "Invalid password format: it must contain at least 8 characters, one uppercase letter, one lowercase letter, one number and one special character",
    PasswordRequired: "The password is required",
    NameRequired: "The name is required",
    TokenRequired: "The Code is required",
    EmailAlreadyExists: "This email is already in use",
    NoTokenProvided: "No token provided",
    UserNotFound: "User not found",
    InactiveUser: "This user is inactive",
    InvalidToken: "The token provided is invalid",
    InvalidResetToken: "The reset code provided is invalid",
    InternalError: "Internal server error, please try again later or contact support",
    ErrorLoggingIn: "Error logging in, please try again later",
    ErrorSendingEmail: "Error sending email",
    ErrorUpdatingPassword: "Error updating password",
    ErrorRegistering: "Error registering",
};
