export default {
    Email: "Correo",
    Password: "Contraseña",
    Login: "Iniciar sesión",
    Register: "Registrarse",
    ForgotPassword: "Olvidé mi contraseña",
    ResetPassword: "Restablecer la contraseña",
    ForgotPasswordLink: "¿Olvidaste tu contraseña?",
    AlreadyHaveAnAccount: "¿Ya tienes una cuenta?",
    DontHaveAnAccount: "¿No tienes una cuenta?",
    RememberMe: "Recuérdame",
    AlreadyHaveToken: "¿Ya tienes el código?",
    BackToLogin: "Volver al inicio de sesión",
    Send: "Enviar",
    ForgotPasswordHelper: "Ingresa tu correo electrónico y te enviaremos un código para restablecer tu contraseña",
    ResetPasswordHelper1: "Ingresa el código y tu nueva contraseña",
    ResetPasswordHelper2: "Ingresa tu correo electrónico, el código y tu nueva contraseña",
    RepeatPassword: "Repetir contraseña",
    Code: "Código",
    PasswordsDontMatch: "Las contraseñas no coinciden",
    Name: "Nombre",
    EmailSent: "Correo enviado",
    CheckEmailToResetPassword: "Revisa tu correo para restablecer tu contraseña",
    PasswordUpdated: "Contraseña actualizada",
    YouCanNowLogin: "Ahora puedes iniciar sesión con tu nueva contraseña",
};
